import Head from "next/head";
import Image from "next/image";
import { Schibsted_Grotesk, IBM_Plex_Mono } from "next/font/google";
import dynamic from "next/dynamic";

const geistSans = Schibsted_Grotesk({
  variable: "--font-body",
  subsets: ["latin"],
});

const geistMono = IBM_Plex_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["400"],
});

const Scene = dynamic(() => import("@/components/Scene/Scene"), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Ryo's 3D Web Sketchbook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{ position: "fixed", inset: 0 }}
      >
        <Scene />
      </div>
    </>
  );
}
